init.d: write logic for radiusd user managment, freeradius: up to 3.0.12 version.

diff --git a/user/freeradius/install-sh b/user/freeradius/install-sh
--- a/user/freeradius/install-sh
+++ b/user/freeradius/install-sh
@@ -129,7 +129,7 @@ Environment variables override the default commands:
 "
 
 while test $# -ne 0; do
-  case $1 in
+    case $1 in
     -c) ;;
 
     -C) copy_on_change=true;;
@@ -150,7 +150,7 @@ while test $# -ne 0; do
 	esac
 	shift;;
 
-    -o) chowncmd="$chownprog $2"
+	-o) chowncmd="$chownprog $2"
 	shift;;
 
     -s) stripcmd=$stripprog;;
@@ -174,7 +174,7 @@ while test $# -ne 0; do
 
     *)  break;;
   esac
-  shift
+	    shift
 done
 
 if test $# -ne 0 && test -z "$dir_arg$dst_arg"; then
@@ -194,13 +194,13 @@ if test $# -ne 0 && test -z "$dir_arg$dst_arg"; then
     case $dst_arg in
       -* | [=\(\)!]) dst_arg=./$dst_arg;;
     esac
-  done
+done
 fi
 
 if test $# -eq 0; then
   if test -z "$dir_arg"; then
     echo "$0: no input file specified." >&2
-    exit 1
+	exit 1
   fi
   # It's OK to call 'install-sh -d' without argument.
   # This can happen when creating conditional directories.
@@ -231,12 +231,12 @@ if test -z "$dir_arg"; then
     *)
       if test -z "$stripcmd"; then
 	u_plus_rw=
-      else
+	else
 	u_plus_rw=,u+rw
       fi
       cp_umask=$mode$u_plus_rw;;
   esac
-fi
+	fi
 
 for src
 do
@@ -250,20 +250,20 @@ do
     dstdir=$dst
     test -d "$dstdir"
     dstdir_status=$?
-  else
+else
 
     # Waiting for this to be detected by the "$cpprog $src $dsttmp" command
-    # might cause directories to be created, which would be especially bad
-    # if $src (and thus $dsttmp) contains '*'.
+# might cause directories to be created, which would be especially bad 
+# if $src (and thus $dsttmp) contains '*'.
     if test ! -f "$src" && test ! -d "$src"; then
       echo "$0: $src does not exist." >&2
-      exit 1
-    fi
-
+		exit 1
+	fi
+	
     if test -z "$dst_arg"; then
       echo "$0: no destination specified." >&2
-      exit 1
-    fi
+		exit 1
+	fi
     dst=$dst_arg
 
     # If destination is a directory, append the input filename; won't work
@@ -306,8 +306,8 @@ do
 
       test -d "$dstdir"
       dstdir_status=$?
-    fi
-  fi
+	fi
+fi
 
   obsolete_mkdir_used=false
 
@@ -350,7 +350,7 @@ do
 
 	    if (umask $mkdir_umask &&
 		exec $mkdirprog $mkdir_mode -p -- "$tmpdir/d") >/dev/null 2>&1
-	    then
+        then
 	      if test -z "$dir_arg" || {
 		   # Check for POSIX incompatibilities with -m.
 		   # HP-UX 11.23 and IRIX 6.5 mkdir -m -p sets group- or
@@ -368,12 +368,12 @@ do
 		   }
 		 }
 	      then posix_mkdir=:
-	      fi
+	fi
 	      rmdir "$tmpdir/d" "$tmpdir"
 	    else
 	      # Remove any dirs left behind by ancient mkdir implementations.
 	      rmdir ./$mkdir_mode ./-p ./-- 2>/dev/null
-	    fi
+fi
 	    trap '' 0;;
 	esac;;
     esac
@@ -427,7 +427,7 @@ do
 	      *) qprefix=$prefix;;
 	    esac
 	    prefixes="$prefixes '$qprefix'"
-	  fi
+	fi
 	fi
 	prefix=$prefix/
       done
@@ -461,8 +461,8 @@ do
 
     # and set any options; do chmod last to preserve setuid bits.
     #
-    # If any of these fail, we abort the whole thing.  If we want to
-    # ignore errors from any of these, just make sure not to ignore
+# If any of these fail, we abort the whole thing.  If we want to
+# ignore errors from any of these, just make sure not to ignore
     # errors from the above "$doit $cpprog $src $dsttmp" command.
     #
     { test -z "$chowncmd" || $doit $chowncmd "$dsttmp"; } &&
